name: Scheduled Rebuild

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  rebuild:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'

      - name: Trigger Rebuild
        run: |
          git commit --allow-empty -m "Daily Scheduled Rebuild"
          git push origin main
